INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001868', 'Prang Dustless Chalk Sticks');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004876', 'Wilson Jones Suede Grain Vinyl Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000206', 'GE General Purpose, Extra Long Life, Showcase & Floodlight Incandescent Bulbs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003251', 'Prang Drawing Pencil Set');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002255', 'Newell 346');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002988', 'Ideal Clamps');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003622', 'Bravo II Megaboss 12-Amp Hard Body Upright, Replacement Belts, 2 Belts per Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003657', 'Xerox 1927');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10003059', 'Assorted Color Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10003059', 'Assorted Color Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000304', 'Advantus Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000304', 'Advantus Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002049', 'UniKeep View Case Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002012', 'Wilson Jones Easy Flow II Sheet Lifters');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002804', 'Faber Castell Col-Erase Pencils');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001626', 'Commercial WindTunnel Clean Air Upright Vacuum, Replacement Belts, Filtration Bags');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000840', 'OIC Thumb-Tacks');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000206', 'GE General Purpose, Extra Long Life, Showcase & Floodlight Incandescent Bulbs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003602', 'Quartet Omega Colored Chalk, 12/Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001706', 'Longer-Life Soft White Bulbs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10000452', 'Avery 488');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002764', 'Recycled Pressboard Report Cover with Reinforced Top Hinge');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004967', 'Round Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004983', 'Xerox 23');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000304', 'Xerox 1995');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003424', '"While you Were Out" Message Book, One Form per Page');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002897', 'Black Avery Memo-Size 3-Ring Binder, 5 1/2" x 8 1/2"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000585', 'OIC Bulk Pack Metal Binder Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004272', 'Newell 308');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002185', 'QVS USB Car Charger 2-Port 2.1Amp for iPod/iPhone/iPad/iPad 2/iPad 3');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003720', 'Avery 487');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10001404', 'Avery 517');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10000443', 'Avery 501');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003856', 'Newell 344');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10001935', 'Staple remover');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002194', 'Cardinal Hold-It CD Pocket');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000831', 'Storex Flexible Poly Binders with Double Pockets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000940', 'Newell 343');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003727', 'Avery Durable Slant Ring Binders With Label Holder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004970', 'ACCOHIDE 3-Ring Binder, Blue, 1"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002557', 'Presstex Flexible Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10004425', 'Staple-on labels');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10002973', 'Ampad #10 Peel & Seel Holiday Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002741', 'Xerox 1980');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003893', 'Xerox 1962');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001553', 'SpineVue Locking Slant-D Ring Binders by Cardinal');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001706', 'Longer-Life Soft White Bulbs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002701', 'Alliance Rubber Bands');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10001574', 'Acme Value Line Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10001574', 'Acme Value Line Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000702', 'Square Credit Card Reader, 4 1/2" x 4 1/2" x 1", White');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002983', 'Advantus SlideClip Paper Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002432', 'Wilson Jones Standard D-Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10004248', 'Advantus T-Pin Paper Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004967', 'Round Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001982', 'Wilson Jones Custom Binder Spines & Labels');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000546', 'Avery Durable Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003845', 'Xerox 1987');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001838', 'Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 300/Messages');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000605', 'Acco Pressboard Covers with Storage Hooks, 9 1/2" x 11", Executive Red');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003056', 'Newell 341');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001246', 'Newell 317');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002071', 'Fellowes Black Plastic Comb Bindings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001492', 'Acco Six-Outlet Power Strip, 4' Cord Length');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10002195', 'Avery 481');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000735', 'Staples');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000304', 'Advantus Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001227', 'Newell 338');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003429', 'Cardinal HOLDit! Binder Insert Strips,Extra Strips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10001509', 'Poly String Tie Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001593', 'Xerox 1947');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000232', 'Xerox 1975');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003349', 'Xerox 1957');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000390', 'Newell Chalk Holder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004101', 'Xerox 1894');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000552', 'Xerox 200');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001166', 'Xerox 2');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000019', 'Xerox 1931');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003172', 'Xerox 1996');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10000305', 'Avery 495');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003691', 'Eldon Image Series Desk Accessories, Ebony');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004285', 'Xerox 1959');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003001', 'Xerox 1986');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003759', 'Crayola Anti Dust Chalk, 12/Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004610', 'Xerox 1900');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000138', 'Acco Translucent Poly Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10001561', 'Stockwell Push Pins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000546', 'Avery Durable Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002713', 'Adams Phone Message Book, 200 Message Capacity, 8 1/16� x 11�');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003196', 'Accohide Poly Flexible Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10002034', 'Avery 478');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000587', 'Array Parchment Paper, Assorted Colors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002813', 'Avery Reinforcements for Hole-Punch Pages');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000050', 'Angle-D Binders with Locking Rings, Label Holders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003077', 'Avery 500');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001892', 'Rediform Wirebound "Phone Memo" Message Book, 11 x 5-3/4');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000343', 'Pressboard Covers with Storage Hooks, 9 1/2" x 11", Light Blue');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003036', 'Black Print Carbonless 8 1/2" x 8 1/4" Rapid Memo Book');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004656', 'Peel & Stick Add-On Corner Pockets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002018', 'AmazonBasics 3-Button USB Wired Mouse');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004082', 'Adams Telephone Message Book w/Frequently-Called Numbers Space, 400 Messages per Book');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002780', 'Staples');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001149', 'Sanford Colorific Colored Pencils, 12/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000069', 'GBC Prepunched Paper, 19-Hole, for Binding Systems, 24-lb');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000246', 'Newell 318');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001116', 'Wilson Jones 1" Hanging DublLock Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001025', 'Eldon Im�ge Series Desk Accessories, Clear');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003063', 'EcoTones Memo Sheets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002799', 'SlimView Poly Binder, 3/8"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002852', 'Ibico Standard Transparent Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002012', 'Wilson Jones Easy Flow II Sheet Lifters');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002012', 'Wilson Jones Easy Flow II Sheet Lifters');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000773', 'Insertable Tab Post Binder Dividers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004826', 'JM Magazine Binder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003016', 'Adams "While You Were Out" Message Pads');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002804', 'Faber Castell Col-Erase Pencils');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001918', 'C-Line Cubicle Keepers Polyproplyene Holder With Velcro Backings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000546', 'Avery Durable Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002983', 'Advantus SlideClip Paper Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000174', 'Wilson Jones Clip & Carry Folder Binder Tool for Ring Binders, Clear');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000404', 'Avery Printable Repositionable Plastic Tabs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003291', 'Wilson Jones Leather-Like Binders with DublLock Round Rings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002103', 'Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002103', 'Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002071', 'Fellowes Black Plastic Comb Bindings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000585', 'OIC Bulk Pack Metal Binder Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003305', 'Avery Hanging File Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10000089', 'Acco Glide Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002893', 'Wirebound Service Call Books, 5 1/2" x 4"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002893', 'Wirebound Service Call Books, 5 1/2" x 4"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10003072', 'Peel & Seel Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003363', 'Xerox 204');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002262', 'Xerox 192');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003309', 'Xerox 211');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000477', 'Xerox 22');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001166', 'Xerox 2');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002766', 'Prang Drawing Pencil Set');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002766', 'Prang Drawing Pencil Set');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002230', 'Xerox 1897');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004728', 'Wilson Jones Turn Tabs Binder Tool for Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000743', 'Xerox 1977');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002947', 'Xerox 1923');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001804', 'Xerox 195');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002986', 'Xerox 1898');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001246', 'Newell 317');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001525', 'Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Executive Red');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002003', 'Ibico Presentation Index for Binding Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002003', 'Ibico Presentation Index for Binding Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002957', 'Sterilite Show Offs Storage Containers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000157', 'Xerox 191');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10000407', 'Avery White Multi-Purpose Labels');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000174', 'Message Book, Wirebound, Four 5 1/2" X 4" Forms/Pg., 200 Dupl. Sets/Book');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000320', 'GBC Plastic Binding Combs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002445', 'DAX Two-Tone Rosewood/Black Document Frame, Desktop, 5 x 7');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002215', 'Wilson Jones Hanging View Binder, White, 1"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001424', 'Dax Clear Box Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004156', 'Xerox 188');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002309', 'Avery Heavy-Duty EZD  Binder With Locking Rings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000528', 'Xerox 1981');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10003134', 'Staple envelope');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10003134', 'Staple envelope');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10001219', '#10- 4 1/8" x 9 1/2" Security-Tint Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001892', 'Rediform Wirebound "Phone Memo" Message Book, 11 x 5-3/4');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004052', 'Hoover Replacement Belts For Soft Guard & Commercial Ltweight Upright Vacs, 2/Pk');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003190', 'Avery 474');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003036', 'Black Print Carbonless 8 1/2" x 8 1/4" Rapid Memo Book');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000682', 'Xerox 1924');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003016', 'Adams "While You Were Out" Message Pads');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000896', 'Newell 329');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000203', 'Newell 336');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10004854', 'Vinyl Coated Wire Paper Clips in Organizer Box, 800/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001947', 'Xerox 1974');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001536', 'Spigen Samsung Galaxy S5 Case Wallet');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004965', 'Ibico Covers for Plastic or Wire Binding Elements');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004785', 'Holmes Replacement Filter for HEPA Air Cleaner, Medium Room');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003355', 'Cardinal Holdit Business Card Pockets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000171', 'Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 25/Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004209', 'Fellowes Twister Kit, Gray/Clear, 3/pkg');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003514', '4009 Highlighters by Sanford');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004665', 'Advantus Motivational Note Cards');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001940', 'Staple-based wall hangings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000804', 'Hoover Portapower Portable Vacuum');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004752', 'Blackstonian Pencils');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004930', 'Turquoise Lead Holder with Pocket Clip');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002005', 'Xerox 225');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001800', 'Xerox 220');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001972', 'Xerox 214');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002262', 'Xerox 192');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003194', 'Eldon Expressions Desk Accessory, Wood Pencil Holder, Oak');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004094', 'GBC Standard Plastic Binding Systems Combs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001249', 'Avery Heavy-Duty EZD View Binder with Locking Rings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003651', 'Xerox 1968');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004632', 'GBC Binding covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002254', 'Xerox 1883');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003731', 'Eldon Expressions Wood and Plastic Desk Accessories, Oak');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10002195', 'Avery 481');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004654', 'Avery Binding System Hidden Tab Executive Style Index Sets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000575', 'Wirebound Message Books, Four 2 3/4 x 5 White Forms per Page');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004000', 'While You Were Out Pads, 50 per Pad, 4 x 5 1/4, Green Cycle');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002606', 'Xerox 1928');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004911', 'Rediform S.O.S. 1-Up Phone Message Bk, 4-1/4x3-1/16 Bk, 1 Form/Pg, 40 Messages/Bk, 3/Pk');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003829', 'Stackable Trays');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10004544', 'Avery 505');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003923', 'Alphabetical Labels for Top Tab Filing');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000174', 'Wilson Jones Clip & Carry Folder Binder Tool for Ring Binders, Clear');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002893', 'Wirebound Service Call Books, 5 1/2" x 4"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000321', 'Akro Stacking Bins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003504', 'Newell 347');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004963', 'Eldon 400 Class Desk Accessories, Black Carbon');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001867', 'Eldon Expressions Punched Metal & Wood Desk Accessories, Pewter & Cherry');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002215', 'Wilson Jones Hanging View Binder, White, 1"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002215', 'Wilson Jones Hanging View Binder, White, 1"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000309', 'GBC Twin Loop Wire Binding Elements, 9/16" Spine, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000309', 'GBC Twin Loop Wire Binding Elements, 9/16" Spine, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002088', 'Nu-Dell Float Frame 11 x 14 1/2');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002071', 'Fellowes Black Plastic Comb Bindings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003988', 'LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003560', 'Zebra Zazzle Fluorescent Highlighters');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002949', 'Prestige Round Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001149', 'Sanford Colorific Colored Pencils, 12/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004864', 'Eldon 500 Class Desk Accessories');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004041', 'It's Hot Message Books with Stickers, 2 3/4" x 5"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000246', 'Riverleaf Stik-Withit Designer Note Cubes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004078', 'Newell 312');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004351', 'Staple-based wall hangings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10001641', 'Avery 518');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001095', 'DAX Black Cherry Wood-Tone Poster Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000023', 'Eldon Wave Desk Accessories');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002456', 'Master Caster Door Stop, Large Neon Orange');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000550', 'Stacking Trays by OIC');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003628', 'Logitech 910-002974 M325 Wireless Mouse for Web Scrolling');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001870', 'Xerox 202');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001569', 'Xerox 232');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004609', 'Xerox 221');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003281', 'Acco 6 Outlet Guardian Standard Surge Suppressor');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000241', 'IBM Multi-Purpose Copy Paper, 8 1/2 x 11", Case');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000914', 'Boston 16765 Mini Stand Up Battery Pencil Sharpener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002986', 'Xerox 1898');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000347', 'Cush Cases Heavy Duty Rugged Cover Case for Samsung Galaxy S5 - Purple');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000794', 'Eldon Stackable Tray, Side-Load, Legal, Smoke');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-FA-10002280', 'Advantus Plastic Paper Clips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001044', 'BOSTON Ranger #55 Pencil Sharpener, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000755', 'Eldon Expressions Mahogany Wood Desk Collection');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002377', 'Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 200/Messages');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001736', 'Xerox 1880');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004965', 'Ibico Covers for Plastic or Wire Binding Elements');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001900', 'DXL Angle-View Binders with Locking Rings, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000050', 'Angle-D Binders with Locking Rings, Label Holders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001970', 'Xerox 1881');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001970', 'Xerox 1881');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002036', 'Xerox 1930');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10004290', 'Acme Design Line 8" Stainless Steel Bent Scissors w/Champagne Handles, 3-1/8" Cut');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10002503', 'Acme Preferred Stainless Steel Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003878', 'Linden 10" Round Wall Clock, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001918', 'C-Line Cubicle Keepers Polyproplyene Holder With Velcro Backings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003072', 'Eureka Recycled Copy Paper 8 1/2" x 11", Ream');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001419', 'Newell 325');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004041', 'It's Hot Message Books with Stickers, 2 3/4" x 5"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000807', 'TOPS "Important Message" Pads, Canary, 4-1/4 x 5-1/2, 50 Sheets per Pad');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002464', 'HP Office Recycled Paper (20Lb. and 87 Bright)');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002160', 'Xerox 1978');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10002557', 'Fiskars Spring-Action Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000357', 'White Dual Perf Computer Printout Paper, 2700 Sheets, 1 Part, Heavyweight, 20 lbs., 14 7/8 x 11');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003399', 'Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002571', 'Avery Framed View Binder, EZD Ring (Locking), Navy, 1 1/2"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10001158', 'Avery Address/Shipping Labels for Typewriters, 4" x 2"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10004231', 'Acme Tagit Stainless Steel Antibacterial Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004351', 'Staple-based wall hangings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004973', 'Flat Face Poster Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004671', 'Executive Impressions 12" Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001679', 'GBC Instant Index System for Binding Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001706', 'Longer-Life Soft White Bulbs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003156', '50 Colored Long Pencils');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003305', 'Avery Hanging File Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10000946', 'Staple remover');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000948', 'GBC Laser Imprintable Binding System Covers, Desert Sand');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000321', 'Akro Stacking Bins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001325', 'Sterilite Officeware Hinged File Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10000461', '#10- 4 1/8" x 9 1/2" Recycled Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003077', 'Avery 500');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000019', 'Xerox 1931');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004735', 'Xerox 1905');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004101', 'Xerox 1894');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002352', 'Iris Project Case');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000213', 'Xerox 198');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003971', 'Belkin 6 Outlet Metallic Surge Strip');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000918', 'Crate-A-Files');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003651', 'Xerox 1968');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001958', 'Stanley Bostitch Contemporary Electric Pencil Sharpeners');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001958', 'Stanley Bostitch Contemporary Electric Pencil Sharpeners');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002923', 'Xerox 1942');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001776', 'Wirebound Message Books, Four 2 3/4" x 5" Forms per Page, 600 Sets per Book');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002824', 'Recycled Easel Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004848', 'DAX Solid Wood Frames');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003442', 'Samsung Replacement EH64AVFWE Premium Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003976', 'DAX Executive Solid Wood Document Frame, Desktop or Hang, Mahogany, 5 x 7');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000658', 'Newell 324');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000380', 'REDIFORM Incoming/Outgoing Call Register, 11" X 8 1/2", 100 Messages');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10004507', 'Advantus Rolling Storage Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002214', 'X-Rack File for Hanging Folders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10003123', 'Fellowes Bases and Tops For Staxonsteel/High-Stak Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10003123', 'Fellowes Bases and Tops For Staxonsteel/High-Stak Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000148', 'Cyber Acoustics AC-202b Speech Recognition Stereo Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004734', 'Southworth Structures Collection');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001294', 'Fellowes Binding Cases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002167', 'Imation�8gb Micro Traveldrive Usb 2.0�Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000023', 'Maxell 74 Minute CD-R Spindle, 50/Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001658', 'GBC Standard Therm-A-Bind Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10001158', 'Avery Address/Shipping Labels for Typewriters, 4" x 2"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004100', 'Xerox 216');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002350', 'Belkin F9H710-06 7 Outlet SurgeMaster Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000777', 'Companion Letter/Legal File, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003577', 'Nu-Dell Leatherette Frames');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004666', 'DAX Clear Channel Poster Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001558', 'Acco Perma 4000 Stacking Storage Drawers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004091', 'Howard Miller 13" Diameter Goldtone Round Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003622', 'Bravo II Megaboss 12-Amp Hard Body Upright, Replacement Belts, 2 Belts per Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10003837', 'Anderson Hickey Conga Table Tops & Accessories');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003291', 'Wilson Jones Leather-Like Binders with DublLock Round Rings');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10002500', 'Globe Weis Peel & Seel First Class Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003499', 'Memorex Mini Travel Drive 8 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003127', 'Easy-staple paper');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001628', 'Acco Data Flex Cable Posts For Top & Bottom Load Binders, 6" Capacity');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001977', 'Xerox 194');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10002592', 'Peel & Seel Recycled Catalog Envelopes, Brown');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10004963', 'Eldon Gobal File Keepers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001615', 'Newell 34');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10004544', 'Avery 505');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004897', 'Mediabridge Sport Armband iPhone 5s');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002498', 'Clear Mylar Reinforcing Strips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004090', 'Executive Impressions 14" Contract Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003166', 'GBC Plasticlear Binding Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003903', 'Sanford 52201 APSCO Electric Pencil Sharpener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003364', 'Binding Machine Supplies');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003364', 'Binding Machine Supplies');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002445', 'SANFORD Major Accent Highlighters');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003289', 'Anker Ultra-Slim Mini Bluetooth 3.0 Wireless Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000011', 'PureGear Roll-On Screen Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003638', 'GBC Durable Plastic Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002429', 'Premier Elliptical Ring Binder, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000157', 'Xerox 191');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001492', 'Acco Six-Outlet Power Strip, 4' Cord Length');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001036', 'Cardinal EasyOpen D-Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001460', 'Plastic Binding Combs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001460', 'Plastic Binding Combs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002225', 'Square Ring Data Binders, Rigid 75 Pt. Covers, 11" x 14-7/8"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001575', 'GBC Linen Binding Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003171', 'Plantronics Encore H101 Dual Earpieces�Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000615', 'SimpliFile Personal File, Black Granite, 15w x 6-15/16d x 11-1/4h');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002824', 'Recycled Easel Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001078', 'Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 14 7/8" X 11"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003628', 'Logitech 910-002974 M325 Wireless Mouse for Web Scrolling');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002852', 'Ibico Standard Transparent Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002852', 'Ibico Standard Transparent Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000483', 'Xerox 19');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10003638', 'Mobile Personal File Cube');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001153', 'Ibico Recycled Grain-Textured Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000285', 'XtraLife ClearVue Slant-D Ring Binders by Cardinal');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000649', 'Hanging Personal Folder File');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003166', 'GBC Plasticlear Binding Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000876', 'Eldon Simplefile Box Office');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004833', 'Macally Suction Cup Mount');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004230', 'GBC Recycled Grain Textured Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001765', 'Wilson Jones Heavy-Duty Casebound Ring Binders with Metal Hinges');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001765', 'Wilson Jones Heavy-Duty Casebound Ring Binders with Metal Hinges');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10004231', 'Acme Tagit Stainless Steel Antibacterial Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004848', 'Howard Miller 13-3/4" Diameter Brushed Chrome Round Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003038', 'Kingston Digital DataTraveler 16GB USB 2.0');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004071', 'PayAnywhere Card Reader');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001958', 'Stanley Bostitch Contemporary Electric Pencil Sharpeners');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000387', 'KeyTronic�KT800P2 -�Keyboard�- Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10001099', 'Staple envelope');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000595', 'Xerox 1929');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002718', 'Belkin Standard 104 key USB Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001670', 'Vinyl Sectional Post Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000148', 'Cyber Acoustics AC-202b Speech Recognition Stereo Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004042', 'BOSTON Model 1800 Electric Pencil Sharpeners, Putty/Woodgrain');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001363', 'Xerox 1933');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001013', 'Logitech ClearChat Comfort/USB Headset H390');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001998', 'Logitech�LS21 Speaker System - PC Multimedia - 2.1-CH - Wired');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000023', 'Eldon Wave Desk Accessories');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10000946', 'Staple remover');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002445', 'DAX Two-Tone Rosewood/Black Document Frame, Desktop, 5 x 7');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000014', 'Heavy-Duty E-Z-D Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10003582', 'Boston Electric Pencil Sharpener, Model 1818, Charcoal Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002026', 'Ibico Recycled Linen-Style Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002486', 'Eldon Shelf Savers Cubes and Bins');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10003442', 'Eldon Portable Mobile Manager');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000943', 'Eldon ProFile File 'N Store Portable File Tub Letter/Legal Size Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000943', 'Eldon ProFile File 'N Store Portable File Tub Letter/Legal Size Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003007', 'Premium Transparent Presentation Covers, No Pattern/Clear, 8 1/2" x 11"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000307', 'Shocksock Galaxy S4 Armband');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000174', 'Wilson Jones Clip & Carry Folder Binder Tool for Ring Binders, Clear');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003656', 'Xerox 1935');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003266', 'Holmes Replacement Filter for HEPA Air Cleaner, Large Room');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002485', 'Rogers Deluxe File Chest');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001524', 'GBC Premium Transparent Covers with Diagonal Lined Pattern');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000588', 'Newell 345');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004090', 'Executive Impressions 14" Contract Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10002666', 'Southworth 25% Cotton Linen-Finish Paper & Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000076', '24-Hour Round Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004036', 'Bionaire 99.97% HEPA Air Cleaner');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001870', 'Lunatik TT5L-002 Taktik Strike Impact Protection System for iPhone 5');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004666', 'DAX Clear Channel Poster Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003289', 'Anker Ultra-Slim Mini Bluetooth 3.0 Wireless Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002353', 'GBC VeloBind Cover Sets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000672', 'Executive Impressions 10" Spectator Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10004773', 'Staple envelope');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10001218', 'Fiskars Softgrip Scissors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004833', 'Macally Suction Cup Mount');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004093', 'Hand-Finished Solid Wood Document Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001750', 'Samsung Rugby III');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000636', 'Rogers Profile Extra Capacity Storage Tub');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002670', 'Belkin 8-Outlet Premiere SurgeMaster II Surge Protectors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000977', 'Ibico Plastic Spiral Binding Combs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001095', 'DAX Black Cherry Wood-Tone Poster Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001295', 'Computer Printout Paper with Letter-Trim Perforations');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000315', 'Poly Designer Cover & Back');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004781', 'GBC Wire Binding Strips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10004602', 'Boston KS Multi-Size Manual Pencil Sharpener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004327', 'Xerox 1911');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004381', '14-7/8 x 11 Blue Bar Computer Printout Paper');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004492', 'Tuf-Vin Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004767', 'Safco Drafting Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001465', 'SanDisk Cruzer 64 GB USB Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000167', 'Xerox 1925');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001125', 'Xerox 1988');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004353', 'Southworth 25% Cotton Premium Laser Paper and Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004308', 'Avery Legal 4-Ring Binder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002726', 'netTALK DUO VoIP Telephone Service');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000087', 'Executive Impressions 14" Two-Color Numerals Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003719', 'Large Capacity Hanging Post Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000418', 'Xerox 189');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001524', 'GBC Premium Transparent Covers with Diagonal Lined Pattern');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002554', 'Westinghouse Floor Lamp with Metal Mesh Shade, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004475', 'Xerox 1940');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002335', 'Logitech Media Keyboard K200');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003039', 'Howard Miller 11-1/2" Diameter Grantwood Wall Clock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000532', 'Advantus Rolling Drawer Organizers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004039', 'Xerox 1882');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000806', 'Xerox 1934');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000892', 'NETGEAR N750 Dual Band Wi-Fi Gigabit Router');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10001615', 'Newell 34');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001469', 'Fellowes 8 Outlet Superior Workstation Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001289', 'White Computer Printout Paper by Universal');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004532', 'Kensington 6 Outlet Guardian Standard Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000798', '2300 Heavy-Duty Transfer File Systems by Perma');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004249', 'Staple holder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000312', 'Xerox 1955');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002583', 'Fellowes Neat Ideas Storage Cubes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003610', 'Logitech�Illuminated - Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003638', 'GBC Durable Plastic Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000675', 'Xerox 1919');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001033', 'Xerox 1893');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003198', 'Enermax Acrylux Wireless Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002564', 'OtterBox Defender Series Case - Samsung Galaxy S4');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001510', 'Deluxe Heavy-Duty Vinyl Round Ring Binder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10001889', 'Ultra Door Pull Handle');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001366', 'Staple holder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000358', 'Fellowes Basic Home/Office Series Surge Protectors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001908', 'Logitech Wireless Headset h800');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004093', 'Panasonic Kx-TS550');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004781', 'GBC Wire Binding Strips');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002890', 'AT&T 17929 Lendline Telephone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001553', 'Memorex 25GB 6X Branded Blu-Ray Recordable Disc, 15/Pack');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10004469', 'Microsoft Sculpt Comfort Mouse');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10004469', 'Microsoft Sculpt Comfort Mouse');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001321', 'Decoflex Hanging Personal Folder File, Blue');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000696', 'Holmes Odor Grabber');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003396', 'Global Deluxe Steno Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000526', 'Vtech CS6719');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004249', 'Staple holder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000632', 'Satellite Sectional Post Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000057', 'Microsoft Natural Ergonomic Keyboard 4000');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002774', 'Global Deluxe Stacking Chair, Gray');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002578', 'Fellowes Premier Superior Surge Suppressor, 10-Outlet, With Phone and Remote');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002578', 'Fellowes Premier Superior Surge Suppressor, 10-Outlet, With Phone and Remote');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002961', 'Leather Task Chair, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003061', 'Global Leather Task Chair, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003061', 'Global Leather Task Chair, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004224', 'Catalog Binders with Expanding Posts');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000962', 'Acco Flexible ACCOHIDE Square Ring Data Binder, Dark Blue, 11 1/2" X 14" 7/8"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001815', 'Xerox 1885');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001670', 'Vinyl Sectional Post Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000747', 'Tenex B1-RE Series Chair Mats for Low Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000747', 'Tenex B1-RE Series Chair Mats for Low Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000215', 'Plantronics Cordless�Phone Headset�with In-line Volume - M214C');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002311', 'Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002844', 'Speck Products Candyshell Flip Case');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000736', 'Carina Double Wide Media Storage Towers in Natural & Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10000898', 'Acme Hot Forged Carbon Steel Scissors with Nickel-Plated Handles, 3 7/8" Cut, 8"L');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002923', 'Logitech B530 USB�Headset�-�headset�- Full size, Binaural');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004001', 'GBC Recycled VeloBinder Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002082', 'GBC Twin Loop Wire Binding Elements');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004492', 'Tuf-Vin Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003399', 'Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000109', 'Sony Micro Vault Click 16 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000109', 'Sony Micro Vault Click 16 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003625', 'Xerox 1979');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003876', 'Green Canvas Binder for 8-1/2" x 14" Sheets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004039', 'Xerox 1882');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002952', 'Stanley Contemporary Battery Pencil Sharpeners');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001144', 'Xerox 1913');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001977', 'Xerox 194');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000358', 'Imation�Secure�Drive�+ Hardware Encrypted USB�flash drive�- 16 GB');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001772', 'Memorex Mini Travel Drive 16 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004774', 'Gear Head AU3700S Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001267', 'Imation�32GB Pocket Pro USB 3.0�Flash Drive�- 32 GB - Black - 1 P ...');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10004709', 'Bush Westfield Collection Bookcases, Medium Cherry Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000441', 'VTech DS6151');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002735', 'GBC Prestige Therm-A-Bind Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003817', 'Global Value Steno Chair, Gray');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001146', 'Global Value Mid-Back Manager's Chair, Gray');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000057', 'Microsoft Natural Ergonomic Keyboard 4000');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003171', 'Plantronics Encore H101 Dual Earpieces�Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003171', 'Plantronics Encore H101 Dual Earpieces�Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000865', 'WD My Passport Ultra 500GB Portable External Hard Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003790', 'Xerox 1991');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003684', 'Wilson Jones Legal Size Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002937', 'GE 48" Fluorescent Tube, Cool White Energy Saver, 34 Watts, 30/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001815', 'Xerox 1885');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10003930', 'Dot Matrix Printer Tape Reel Labels, White, 5000/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000988', 'Hon Olson Stacker Stools');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004330', 'GBC Velobind Prepunched Cover Sets, Regency Series');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002660', 'Nortel Networks T7316 E Nt8 B27');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001476', 'Steel Personal Filing/Posting Tote');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000675', 'Xerox 1919');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003800', 'i.Sound Portable Power - 8000 mAh');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003800', 'i.Sound Portable Power - 8000 mAh');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001924', 'iHome FM Clock Radio with Lightning Dock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003657', 'Lenovo 17-Key USB Numeric Keypad');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002370', 'Sortfiler Multipurpose Personal File Organizer, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10000380', 'Hunt PowerHouse Electric Pencil Sharpener, Blue');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002647', 'Situations Contoured Folding Chairs, 4/Set');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001597', 'Wilson Jones Ledger-Size, Piano-Hinge Binder, 2", Blue');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004708', 'Fellowes Superior 10 Outlet Split Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003287', 'Tripp Lite TLP810NET Broadband Surge for Modem/Fax');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001543', 'GBC VeloBinder Manual Binding System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004952', 'C-Line Cubicle Keepers Polyproplyene Holder w/Velcro Back, 8-1/2x11, 25/Bx');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10003641', 'Xerox 1909');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001838', 'Razer Tiamat Over Ear 7.1 Surround Sound PC Gaming Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10004039', 'Xerox 1882');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001970', 'Xerox 1908');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003394', 'Tenex "The Solids" Textured Chair Mats');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002647', 'Logitech�Wireless Boombox Speaker - portable - wireless, wired');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000193', 'Tenex Chairmats For Use with Hard Floors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000991', 'Sony Micro Vault Click 8 GB USB 2.0 Flash Drive');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004960', 'Seth Thomas 12" Clock w/ Goldtone Case');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002217', 'Imation�Clip USB�flash drive�- 8 GB');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001606', 'Logitech Wireless Performance Mouse MX for PC and Mac');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001606', 'Logitech Wireless Performance Mouse MX for PC and Mac');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003040', 'Fellowes 8 Outlet Superior Workstation Surge Protector w/o Phone/Fax/Modem Protection');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001490', 'Hot File 7-Pocket, Floor Stand');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002564', 'OtterBox Defender Series Case - Samsung Galaxy S4');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004477', 'Global Push Button Manager's Chair, Indigo');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002800', 'Plantronics Audio 478 Stereo USB Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003505', 'Geemarc AmpliPOWER60');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10002206', 'Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10002230', 'Airmail Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000785', 'Global Ergonomic Managers Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000863', 'Novimex Swivel Fabric Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AR-10002135', 'Boston Heavy-Duty Trimline Electric Pencil Sharpeners');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001891', 'Global Deluxe Office Fabric Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004593', 'Ibico Laser Imprintable Binding System Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000439', 'GE DSL Phone Line Filter');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004230', 'GBC Recycled Grain Textured Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000036', 'Recycled Data-Pak for Archival Bound Computer Printouts, 12-1/2 x 12-1/2 x 16');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004597', 'Eldon Cleatmat Chair Mats for Medium Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001676', 'Hon 61000 Series Interactive Training Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-LA-10001474', 'Avery 477');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002867', 'Fellowes Command Center 5-outlet power strip');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004152', 'Barricks 18" x 48" Non-Folding Utility Table with Bottom Storage Shelf');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-EN-10003296', 'Tyvek Side-Opening Peel & Seel Expanding Envelopes');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002289', 'Safco Wire Cube Shelving System, For Use as 4 or 5 14" Cubes, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003535', 'Global Armless Task Chair, Royal Blue');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002974', 'Trav-L-File Heavy-Duty Shuttle II, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004754', 'Global Stack Chair with Arms, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002026', 'Avery Arch Ring Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000736', 'Carina Double Wide Media Storage Towers in Natural & Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000604', 'Home/Office Personal File Carts');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003555', 'Motorola HK250 Universal Bluetooth Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10004233', 'Honeywell Enviracaire Portable Air Cleaner for up to 8 x 10 Room');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003268', 'Eldon Radial Chair Mat for Low to Medium Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002800', 'Plantronics Audio 478 Stereo USB Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10000468', 'O'Sullivan 2-Shelf Heavy-Duty Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004593', 'Ibico Laser Imprintable Binding System Covers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003095', 'Logitech G35 7.1-Channel Surround Sound Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001425', 'Mophie Juice Pack Helium for iPhone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10002694', 'Hewlett-Packard Deskjet F4180 All-in-One Color Ink-jet - Printer / copier / scanner');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003394', 'Tenex "The Solids" Textured Chair Mats');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004698', 'Padded Folding Chairs, Black, 4/Carton');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001520', 'Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000390', 'Euro Pro Shark Stick Mini Vacuum');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000441', 'VTech DS6151');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000891', 'Kensington 7 Outlet MasterPiece HOMEOFFICE Power Control Center');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003968', 'Novimex Turbo Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003968', 'Novimex Turbo Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10002794', 'Avery Trapezoid Ring Binder, 3" Capacity, Black, 1040 sheets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004860', 'Global Low Back Tilter Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003174', 'Plantronics S12 Corded Telephone Headset System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10004855', 'V7 USB Numeric Keypad');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001949', 'Cisco SPA 501G IP Phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002926', 'Logitech Wireless Marathon Mouse M705');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001970', 'Xerox 1908');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000576', 'AT&T 1080 Corded phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004086', 'KI Adjustable-Height Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000358', 'Imation�Secure�Drive�+ Hardware Encrypted USB�flash drive�- 16 GB');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004536', 'Avaya 5420 Digital phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004665', '3M Polarizing Task Lamp with Clamp Arm, Light Gray');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001293', 'Belkin 8 Outlet Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004886', 'Bevis Steel Folding Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000526', 'Vtech CS6719');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003833', 'Novimex Fabric Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003833', 'Novimex Fabric Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10001878', 'Xerox 1891');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10003159', 'Sauder Camden County Collection Libraries, Planked Cherry Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001557', 'Pyle PMP37LED');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10000632', 'Satellite Sectional Post Binders');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001051', 'HTC One');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000580', 'Logitech G13 Programmable Gameboard with LCD Display');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004622', 'Eldon Advantage Foldable Chair Mats for Low Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000847', 'Global Executive Mid-Back Manager's Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000844', 'Logitech�Gaming G510s - Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002880', 'Global High-Back Leather Tilter, Burgundy');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10003505', 'Premier Electric Letter Opener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10004975', 'Plantronics Audio 995 Wireless Stereo Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001552', 'Logitech K350 2.4Ghz Wireless Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001307', 'SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001809', 'Panasonic KX T7736-B Digital phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001242', 'APC 7 Outlet Network SurgeArrest Surge Protector');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000240', 'Belkin F9G930V10-GRY 9 Outlet Surge');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001383', 'Logitech Wireless Touch Keyboard K400');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-PA-10000806', 'Xerox 1934');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10001071', 'GBC ProClick Punch Binding System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000747', 'Tenex B1-RE Series Chair Mats for Low Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004626', 'Office Star Flex Back Scooter Chair with Aluminum Finish Frame');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003774', 'Global Wood Trimmed Manager's Task Chair, Khaki');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10003645', 'Aastra 57i VoIP phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002554', 'Tennsco Industrial Shelving');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004345', 'Cisco SPA 502G IP Phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003846', 'Hon Valutask Swivel Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004017', 'Tenex Contemporary Contur Chairmats for Low and Medium Pile Carpet, Computer, 39" x 49"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10002268', 'Sauder Barrister Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001924', 'iHome FM Clock Radio with Lightning Dock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002116', 'Tenex Carpeted, Granite-Look or Clear Contemporary Contour Shape Chair Mats');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10000362', 'Sauder Inglewood Library Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10002622', 'Bush Andora Conference Table, Maple/Graphite Gray Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002647', 'Situations Contoured Folding Chairs, 4/Set');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002600', 'Belkin QODE FastFit Bluetooth Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001496', 'Standard Rollaway File with Lock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002103', 'Jabra SPEAK 410');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004519', 'GBC DocuBind P100 Manual Binding Machine');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10000159', 'Belkin F9M820V08 8 Outlet Surge');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001254', 'Jabra BIZ 2300 Duo QD Duo Corded�Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003374', 'Electrix Fluorescent Magnifier Lamps & Weighted Base');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000892', 'NETGEAR N750 Dual Band Wi-Fi Gigabit Router');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001963', 'Tennsco Regal Shelving Units');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10002937', 'GE 48" Fluorescent Tube, Cool White Energy Saver, 34 Watts, 30/Box');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10003282', 'Advantus 10-Drawer Portable Organizer, Chrome Metal Frame, Smoke Drawers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004922', 'RCA Visys Integrated PBX 8-Line Router');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004218', 'Global Fabric Manager's Chair, Dark Gray');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002049', 'Logitech G19 Programmable Gaming Keyboard');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001713', 'Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5-1/4d x 20-1/2h, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003968', 'Novimex Turbo Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10003159', 'Sauder Camden County Collection Libraries, Planked Cherry Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10001337', 'O'Sullivan Living Dimensions 2-Shelf Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002496', 'Cisco SPA301');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004086', 'KI Adjustable-Height Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004632', 'Ibico Hi-Tech Manual Binding System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10002930', 'Ricoh - Ink Collector Unit for GX3000 Series Printers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001370', 'Sensible Storage WireTech Storage Systems');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002743', 'SAFCO Boltless Steel Shelving');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002103', 'Jabra SPEAK 410');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002789', 'LG Exalt');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002262', 'LG Electronics Tone+ HBS-730 Bluetooth Headset');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004886', 'Bevis Steel Folding Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001557', 'Pyle PMP37LED');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10000157', 'Compact Automatic Electric Letter Opener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001526', 'Iceberg Mobile Mega Data/Printer Cart ');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10001539', 'Logitech G430 Surround Sound Gaming Headset with Dolby 7.1 Technology');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004607', 'Hon 2111 Invitation Series Straight Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002310', 'Panasonic KX T7731-B Digital phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000689', 'Fellowes Strictly Business Drawer File, Letter/Legal Size');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000689', 'Fellowes Strictly Business Drawer File, Letter/Legal Size');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004188', 'Luxo Professional Combination Clamp-On Lamps');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004289', 'BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001391', 'Kensington 6 Outlet MasterPiece HOMEOFFICE Power Control Center');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004667', 'Cisco 8x8 Inc. 6753i IP Business Phone System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003774', 'Global Wood Trimmed Manager's Task Chair, Khaki');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001496', 'Standard Rollaway File with Lock');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004086', 'KI Adjustable-Height Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002945', 'Honeywell Enviracaire Portable HEPA Air Cleaner for 17' x 22' Room');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10002213', 'DMI Eclipse Executive Suite Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000455', 'GE 30522EE2');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001520', 'Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10000330', 'Sauder Camden County Barrister Bookcase, Planked Cherry Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001619', 'LG G3');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-CO-10001943', 'Canon PC-428 Personal Copier');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003708', 'Tenex Traditional Chairmats for Medium Pile Carpet, Standard Lip, 36" x 48"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10003337', 'Okidata B401 Printer');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004147', 'Hon 4060 Series Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002965', 'Global Leather Highback Executive Chair with Pneumatic Height Adjustment, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002415', 'Polycom VoiceStation 500 Conference�phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001530', 'Plantronics Voyager Pro Legend');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000060', 'Fellowes Bankers Box Staxonsteel Drawer File/Stacking System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002076', 'Microsoft Natural Keyboard Elite');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002344', 'Carina 42"Hx23 3/4"W Media Storage Unit');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10004679', 'StarTech.com 10/100 VDSL2 Ethernet Extender Kit');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10003183', 'DYMO CardScan Personal V9 Business Card Scanner');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000293', 'Eldon Antistatic Chair Mats for Low to Medium Pile Carpets');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001190', 'Global Deluxe High-Back Office Chair in Storm');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000229', 'Global Enterprise Series Seating High-Back Swivel/Tilt Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002335', 'Hon GuestStacker Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002335', 'Hon GuestStacker Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001705', 'Bush Advantage Collection Round Conference Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004586', 'Wilson SignalBoost 841262 DB PRO Amplifier Kit');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10001972', 'Okidata C331dn Printer');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004152', 'Barricks 18" x 48" Non-Folding Utility Table with Bottom Storage Shelf');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003956', 'Novimex High-Tech Fabric Mesh Task Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000895', 'Polycom VVX 310 VoIP phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003973', 'GuestStacker Chair with Chrome Finish Legs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002756', 'Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24" Deep, Sand');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10000577', 'Bretford CR4500 Series Slim Rectangular Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000595', 'Safco Contoured Stacking Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001539', 'Chromcraft Rectangular Conference Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001539', 'Chromcraft Rectangular Conference Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10001337', 'O'Sullivan Living Dimensions 2-Shelf Bookcases');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10003650', 'GBC DocuBind 300 Electric Binding Machine');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-CO-10001571', 'Sharp 1540cs Digital Laser Copier');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-CO-10001571', 'Sharp 1540cs Digital Laser Copier');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10003505', 'Premier Electric Letter Opener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10003893', 'Sauder Camden County Collection Library');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001086', 'SAFCO PlanMaster Boards, 60w x 37-1/2d, White Melamine');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002331', 'Hon 4700 Series Mobuis Mid-Back Task Chairs with Adjustable Arms');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001039', 'KI Adjustable-Height Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003761', 'Global Italian Leather Office Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10004306', 'Electrix Halogen Magnifier Lamp');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002292', 'Sauder Facets Collection Locker/File Cabinet, Sky Alder Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003298', 'Office Star - Contemporary Task Swivel chair with Loop Arms, Charcoal');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10000990', 'Imation Bio 2GB USB�Flash Drive Imation�Corp');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004165', 'Mitel MiVoice 5330e IP Phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001768', 'Hon Racetrack Conference Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10002530', 'Iceberg OfficeWorks 42" Round Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10000847', 'Global Executive Mid-Back Manager's Chair');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001545', 'Hon Comfortask Task/Swivel Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10003806', 'Tenex Chairmat w/ Average Lip, 45" x 53"');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002468', 'Plantronics CS 50-USB -�headset�- Convertible, Monaural');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004977', 'GE 30524EE4');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10004695', 'O'Sullivan 2-Door Barrister Bookcase in Odessa Pine');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002049', 'Plantronics Savi W720 Multi-Device Wireless Headset System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000585', 'Economy Rollaway Files');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10001490', 'Hot File 7-Pocket, Floor Stand');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001215', 'Global Troy Executive Leather Low-Back Tilter');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-FU-10000576', 'Luxo Professional Fluorescent Magnifier Lamp with Clamp-Mount Base');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10004619', 'Hon Non-Folding Utility Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10003590', 'Hoover WindTunnel Plus Canister Vacuum');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002743', 'SAFCO Boltless Steel Shelving');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003973', 'GuestStacker Chair with Chrome Finish Legs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10004447', 'Toshiba IPT2010-SD IP�Telephone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10004015', 'Bush Andora Bookcase, Maple/Graphite Gray Finish');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002331', 'Hon 4700 Series Mobuis Mid-Back Task Chairs with Adjustable Arms');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10002637', 'Logitech�VX Revolution Cordless Laser Mouse for Notebooks (Black)');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004495', 'Global Leather and Oak Executive Chair, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10001148', 'Swingline SM12-08 MicroCut Jam Free Shredder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10003569', 'Bretford CR8500 Series Meeting Room Furniture');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10003981', 'Global Commerce Series Low-Back Swivel/Tilt Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001459', 'Samsung Galaxy Mega 6.3');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10002756', 'Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24" Deep, Sand');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002885', 'Apple iPhone 5');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002885', 'Apple iPhone 5');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10002937', 'Canon Color ImageCLASS MF8580Cdw Wireless Laser All-In-One Printer, Copier, Scanner');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10002613', 'Atlantic Metals Mobile 4-Shelf Bookcases, Custom Colors');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001530', 'Cisco Unified IP Phone 7945G VoIP phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-AC-10003832', 'Logitech�P710e Mobile Speakerphone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000078', 'Tennsco 6- and 18-Compartment Lockers');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-ST-10000689', 'Fellowes Strictly Business Drawer File, Letter/Legal Size');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001307', 'SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-BO-10004218', 'Bush Heritage Pine Collection 5-Shelf Bookcase, Albany Pine Finish, *Special Order');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10001578', 'Polycom SoundStation2 EX Conference�phone');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10002903', 'Bevis Round Bullnose 29" High Table Top');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10002684', 'Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10003748', 'Bevis 36 x 72 Conference Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10003979', 'Ativa V4110MDD Micro-Cut Shredder');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-SU-10002881', 'Martin Yale Chadless Opener Electric Letter Opener');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10001695', 'Zebra GK420t Direct Thermal/Thermal Transfer Printer');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002624', 'Samsung Galaxy S4 Mini');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10000488', 'Bady BDG101FRU Card Printer');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-CO-10004115', 'Sharp AL-1530CS Digital Copier');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-AP-10001058', 'Sanyo 2.5 Cubic Foot Mid-Size Office Refrigerators');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10001215', 'Global Troy Executive Leather Low-Back Tilter');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10000560', 'Samsung Galaxy S III - 16GB - pebble blue (T-Mobile)');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10001889', 'Bush Advantage Collection Racetrack Conference Table');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10000864', 'Cisco 9971 IP Video Phone Charcoal');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-TA-10003954', 'Hon 94000 Series Round Tables');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-MA-10004002', 'Zebra GX420t Direct Thermal/Thermal Transfer Printer');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10004086', 'Hon 4070 Series Pagoda Armless Upholstered Stacking Chairs');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-PH-10002200', 'Samsung Galaxy Note 2');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('FUR-CH-10002024', 'HON 5400 Series Task Chairs for Big and Tall');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('OFF-BI-10004995', 'GBC DocuBind P400 Electric Binding System');
INSERT INTO dim_producto (Product_ID, Product_Name) VALUES ('TEC-CO-10004722', 'Canon imageCLASS 2200 Advanced Copier');
