INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Fasteners', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Art', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Labels', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Envelopes', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Paper', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Copiers', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Copiers', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Copiers', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Furnishings', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Accessories', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Storage', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Bookcases', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Supplies', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Copiers', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Appliances', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Home Office');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Tables', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Machines', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Phones', 'Corporate');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Furniture', 'Chairs', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Office Supplies', 'Binders', 'Consumer');
INSERT INTO dim_area (Category, Sub_Category, Segment) VALUES ('Technology', 'Copiers', 'Consumer');
